### ISSUE TITLE
Run example AdvancedEffects for a while (9~66 seconds) may encountered an EXC_BAD_ACCESS exception.

### ISSUE THREAD

**Issue by jacobbubu** [ProjectSeptemberInc/gl-react-native#38] opened 2015-12-03 09:07 UTC
Running on the real device (iPhone6p on iOS 9.1)  with '--dev' flag 'false'.

![bad-access](https://cloud.githubusercontent.com/assets/1164378/11556228/47cacdf0-99e0-11e5-8cce-9bc008edff8d.png)

I've not seen that happened when set '--dev' to 'true'.

**Comment by gre** [comment] 2015-12-03 09:41
what version of gl-react-native ?

**Comment by jacobbubu** [comment] 2015-12-03 09:43
1.3.0

**Comment by gre** [comment] 2015-12-03 09:44
i'm suspecting a race condition with some gl calls that is not running in the gl thread. I've fixed some of these in https://github.com/ProjectSeptemberInc/gl-react-native/commit/e43409fc834e39900b0cc979926f0ebf10151c05 but there might remain bugs. Need to review some code if you confirm this still happens after this commit (1.3.0 should have this commit)

**Comment by gre** [comment] 2015-12-03 09:45
mmh ok. I need to try to reproduce then. thanks for the report

**Comment by jacobbubu** [comment] 2015-12-03 09:49
It won't happen if I comment out "Vignette" and "Slideshow" components in 'src/index.js' render method.

**Comment by gre** [comment] 2015-12-03 09:53
Slideshow might the cause, it swap over a bunch of transitions. Maybe increasing the transition speed can trigger the error more easily? (like `pauseDuration={0} transitionDuration={0.1}` )

**Comment by jacobbubu** [comment] 2015-12-03 09:58
Well the Vignette can also trigger the exception.

**Comment by gre** [comment] 2015-12-03 10:05
do you have this exclusively on the phone or also on the simulator?

**Comment by jacobbubu** [comment] 2015-12-03 10:06
I've just tested on the phone.

**Comment by jacobbubu** [comment] 2015-12-03 10:12
Just tested on the simulator. The exception has also been thrown from the line 391 in GLCanvas.m.

![bad2](https://cloud.githubusercontent.com/assets/1164378/11557765/6d178022-99e9-11e5-9ec3-2e0d8e3264e0.png)

**Comment by gre** [comment] 2015-12-15 11:56
sorry there is something I forgot to ask you.

Do you have any other logs in the console before this happens?

You might have an error like `[warn][tid:main][GLShader.m:78] Shader '<name of the shader>': not a program!`

I suspect https://github.com/ProjectSeptemberInc/gl-react-native/issues/41 will fix it.

**Comment by jacobbubu** [comment] 2015-12-15 15:04
No, I have not seen an error like that.
https://dl.dropboxusercontent.com/u/7632930/Screenshots/Screenshot_2015-12-15_23.02.27.png

**Comment by gre** [comment] 2015-12-15 15:24
Ok thanks. I'll work on this ASAP. This is highest priority on gl-react-native issues.

**Comment by gre** [comment] 2015-12-20 11:05
This should be fixed in https://github.com/ProjectSeptemberInc/gl-react-native/releases/tag/v2.17.0

Feel free to reopen if it's not

**Comment by jacobbubu** [comment] 2015-12-20 13:30
That happened again with the new version (2.17.0)

[Screenshot] https://dl.dropboxusercontent.com/u/7632930/Screenshots/Screenshot_2015-12-20_21.26.25.png

**Comment by gre** [comment] 2015-12-20 14:19
weird.

Can you try to replace https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/Examples/AdvancedEffects/src/index.js#L23

```
      embeddedImage: resolveAssetSource(require("./Image.jpg")),
```

by

```
      embeddedImage: "http://i.imgur.com/2VP5osy.jpg",
```

?

thanks

**Comment by jacobbubu** [comment] 2015-12-21 02:13
Got the same crash with this change.

**Comment by gre** [comment] 2015-12-23 18:05
I can repro on iPhone 6, i'll investigate on this

**Comment by gre** [comment] 2015-12-28 17:00
I've released a **v2.17.2**,
it should fix the crash around `gl_drawArrays` (the one you reported with [this screenshot](https://dl.dropboxusercontent.com/u/7632930/Screenshots/Screenshot_2015-12-15_23.02.27.png)), however there is still the initial crash you reported (the assembly one around `AGXResourceDescriptor::AGXResourceDescriptor`), I have trouble tracing this one...

**Comment by gre** [comment] 2015-12-28 17:49
released a **v2.17.3** which probably fixes the second issue :)

**Comment by jacobbubu** [comment] 2015-12-29 02:01
I've just run AdvancedEffects several times in simulator. The crash did not appear again.

**Comment by gre** [comment] 2015-12-29 08:37
cool! thanks for your help on testing this issue :)
再见 :)

**Closed as completed by gre** 2015-12-29 08:37 UTC
Labels: bug, priority:high
